version: "3"
services:
  app:
    image: daipham99/learning:latest
    container_name: app
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=&sK@rI018r37
      - MYSQL_DATABASE=intern_devops
    volumes:
      - ./docker/database:/var/lib/mysql

